
		<?php
			return
			[
				'general' => 
				[
					'tabHeader' => 'Diesel',
					'date' => 'Dato',
					'back' => 'Tilbage',
					'tab' => 'Advanced',
				],
				'frontpage' => 
				[
					'header' => 'Diesel page',
					'infoHeader' => 'Indtast dine tal nedenfor, og de vil blive vist i tabellen til højre',
					'km' => 'Antal kilometer',
					'liter' => 'Liter',
					'kr' => 'Kroner',
					'enterNumbers' => 'Indsæt tal',
					'tableHeader' => 'Tabel over indtastede diesel tal',
					'deleteRow' => 'Slet række',
					'confirmDelete' => 'Er du sikker på, at du vil slette denne række?',
					'yes' => 'Ja',
					'no' => 'Nej',
					'backButton' => 'Tilbage til startside',
				],
				'dataTable' =>
				[
					'km' => 'Km',
					'liter' => 'Liter',
					'kr' => 'Kroner',
					'kr/l' => 'Kr/L',
					'km/l' => 'Km/L',
					'km/kr' => 'Km/Kr',
					'km/kr' => 'Km/Kr',
					'kr/km' => 'Kr/Km',
					'l/km' => 'L/Km',
					'l/kr' => 'L/Kr',
				],
				'carPage' =>
				[
					'header' => 'Min bil',
					'carAttributes' => 'Attributer for bilen:',
					'type' => 'Art',
					'carType' => 'Personbil',
					'seatNumber' => 'Antal siddepladser inkl. fører: ',
					'seatValue' => '1/5',
					'standNumber' => 'Antal ståpladser:',
					'standValue' => '0',
					'useIndex' => 'Anvendelse:',
					'useValue' => 'Privat personkørsel:',
					'driveForce' => 'Drivkraft:',
					'diesel' => 'Diesel',
					'weightTxt' => 'Køreklar vægt:',
					'weightValue' => '1102kg',
					'gasTxt' => 'Brændstofforbrug:',
					'gasValue' => '25 km/l',
					'axesNumber' => 'Antal akser:',
					'axesValue' => '2',
					'kwTxt' => 'Største effekt (kW) :',
					'kwValue' => '50,0',
					'carModel' => 'Peugeot 206+',
					'backButton' => 'Tilbage',
				],
				'statButtons' =>
				[
					'statistic' => 'Klik her, for at se en mere avanceret statistik',
					'theCar' => 'Klik her, for at se hvilken bil det handler om',
				],
				'advButs' =>
				[
					'backButton' => 'Tilbage',
					'dateStats' => 'Statistik for datoerne',
					'kmStats' => 'Statistik for km',
					'literStats' => 'Statistik for liter',
					'krStats' => 'Statistik for kr',
					'krlStats' => 'Statistik for kr/l',
					'kmlStats' => 'Statistik for km/l',
					'kmKrStats' => 'Statistik for km/kr',
					'customStats' => 'Lav din egen graf',
				],
				'stats' =>
				[
					'header' => 'Avanceret statistik for diesel forbrug',
					'literHeader' => 'Avanceret statistik for antal liter',
					'krlHeader' => 'Avanceret statistik for kroner per liter',
					'kmlHeader' => 'Avanceret statistik for kilometer per liter',
					'krHeader' => 'Avanceret statistik for antal kroner',
					'kmkrHeader' => 'Avanceret statistik for kilometer per kroner',
					'kmHeader' => 'Avanceret statistik for kørte kilometer',
					'dateHeader' => 'Avanceret statistik for dato',
					'kmKr' => 'Km/Kr',
					'krl' => 'Kroner/liter',
					'lkr' => 'liter/kroner',
					'lkm' => 'liter/kilometer',
					'krkm' => 'Kroner/kilometer',
					'kml' => 'Kilometer/liter',
					'kmKr' => 'Kilometer/kroner',
					'stdev' => 'Standard afvigelse',
					'km' => 'Kilometer',
					'liter' => 'Liter',
					'kr' => 'Kroner',
				],
				'graphs' =>
				[
					'dateHeader' => 'Frekvens for dato',
					'literHeader' => 'Frekvens diagram over liter',
					'krlHeader' => 'Frekvens diagram over kroner per liter',
					'krHeader' => 'Frekvens diagram over kroner',
					'freqX' => 'Procent',
					'freqY' => 'Årstal',
					'literY' => 'Liter interval',
					'krlY' => 'Kroner per liter interval',
					'krY' => 'Liter interval',
					'dieselHeader' => 'Diesel regnskab',
					'threeHeader' => 'L/km, l/kr og kr/km',
					'literStdVar' => 'Liter - standard afvigelse og varians',
					'krlStdVar' => 'Kroner per liter - standard afvigelse og varians',
					'krStdVar' => 'Kroner - standard afvigelse og varians',
					'kmlStdVar' => 'Kilometer per liter - standard afvigelse og varians',
					'stdev' => 'Standard afvigelse',
					'averVar' => 'Gennemsnit, varians',
				],
				'dropdown' =>
				[
					'krl' => 'Kroner per liter',
					'kml' => 'Kilometer per liter',
					'kmkr' => 'Kilometer per kroner',
					'lkr' => 'Liter per kroner',
					'lkm' => 'Liter per kilometer',
					'krkm' => 'Kroner per kilometer',
					'km' => 'Kilometer',
					'median' => 'Median',
					'varians' => 'Varians',
					'stdev' => 'St. dev.',
					'average' => 'Gennemsnit',
					'header' => 'Setup din egen graf, ved at vælge fra felterne nederst på siden',
					'short' => 'Kort forklaring',
					'explanation' => 'St dev står for standard deviation, som oversat er standard afvigelse. Den værdi er et udtryk
										for hvor meget alle værdierne fordeler sig omkring deres middelværdi. <br>
										Gen. er en forkortelse for gennemsnittet. <br>
										Median er den midterste værdi af alle værdierne. <br>
										Var står for variansen. Det er en værdi der angiver der angiver variabiliteten af alle værdierne.',
					'curveType' => 'Her kan du vælge om du vil have et søjle diagram, eller en almindelig kurve:',
					'normalCurve' => 'Almindelig funktion',
					'columCurve' => 'Søjlediagram',
					'note' => '(Det virker ikke endnu)',
					'userInput' => 'Bruger input',
					'simpleCalc' => 'Simple beregninger',
					'advCalc' => 'Avancerede beregninger',
					'enterValues' => 'Indtastet værdier',
					'calcValues' => 'Beregnede værdier',
				],
				'ownGraph' =>
				[
					'kmkrHeader' => 'Kilometer per kroner statistik:', 
					'kmkrStdev' => 'Standard afvigelse for kilometer per kroner', 
					'kmkrVar' => 'Varians for kilometer per kroner', 
					'kmkrMedian' => 'Median for kilometer per kroner', 
					'kmkrAverage' => 'Gennemsnit for kilometer per kroner', 
					'kmlHeader' => 'Kilometer per liter statistik:', 
					'kmlStdev' => 'Standard afvigelse for kilometer per liter', 
					'kmlVar' => 'Varians for kilometer per liter', 
					'kmlMedian' => 'Median for kilometer per liter', 
					'kmlAverage' => 'Gennemsnit for kilometer per liter', 
					'krHeader' => 'Kroner statistik:', 
					'krStdev' => 'Standard afvigelse for kroner', 
					'krVar' => 'Varians for kroner', 
					'krMedian' => 'Median for kroner', 
					'krAverage' => 'Gennemsnit for kroner', 
					'krkmHeader' => 'Kroner per kilometer statistik:', 
					'krkmStdev' => 'Standard afvigelse for kroner per kilometer', 
					'krkmVar' => 'Varians for kroner per kilometer', 
					'krkmMedian' => 'Median for kroner per kilometer', 
					'krkmAverage' => 'Gennemsnit for kroner per kilometer', 
					'krlHeader' => 'Kroner per liter statistik:', 
					'krlStdev' => 'Standard afvigelse for kroner per liter', 
					'krlVar' => 'Varians for kroner per liter', 
					'krlMedian' => 'Median for kroner per liter', 
					'krlAverage' => 'Gennemsnit for kroner per liter',
					'lHeader' => 'Liter statistik:', 
					'lStdev' => 'Standard afvigelse liter', 
					'lVar' => 'Varians for liter', 
					'lMedian' => 'Median for liter', 
					'lAverage' => 'Gennemsnit for liter', 
					'lkmHeader' => 'Liter  per kilometer statistik:', 
					'lkmStdev' => 'Standard afvigelse liter per kilometer', 
					'lkmVar' => 'Varians for liter per kilometer', 
					'lkmMedian' => 'Median for liter per kilometer', 
					'lkmAverage' => 'Gennemsnit for liter per kilometer', 
					'lkrHeader' => 'Liter  per kroner statistik:', 
					'lkrStdev' => 'Standard afvigelse liter per kroner', 
					'lkrVar' => 'Varians for liter per kilometer', 
					'lkrMedian' => 'Median for liter per kroner', 
					'lkrAverage' => 'Gennemsnit for liter per kroner', 
					'kmHeader' => 'Kilometer statistik:', 
					'kmStdev' => 'Standard afvigelse kilometer', 
					'kmVar' => 'Varians for kilometer', 
					'kmMedian' => 'Median for kroner', 
					'kmAverage' => 'Gennemsnit for kroner', 
				],
			];
		?>



