	
<?php
	
	$headerArray = [
							"Link", 
							"Kontakt info", 
							"Bilmærke", 
							"Motor", 
							"Pris", 
							"Ny pris", 
							"Pris forskel",
							"Kørte kilometer",
							"Hk/Nm", 
							"Registrerings dato", 
							"Geartype", 
							"0-100 km/t", 
							"Tophastighed", 
							"Drivmiddel", 
							"Forbrug", 
							"Lasteevne", 
							"Trækhjul", 
							"Cylindre", 
							"ABS-bremser", 
							"Max påhæng", 
							"Airbags", 
							"ESP",
                            "Gear",
                            "Tank",
							"Vægt",
							"Døre", 
							"Produktions år", 
							"Modelår", 
							"Synet", 
							"Farve", 
							"Alufælge", 
							"Anhængertræk", 
							"Anhængertræk aftagl.", 
							"Andriod auto", 
							"Antispin", 
							"Apple carplay", 
							"Euronorm", 
							"Bredde", 
							"Længde", 
							"Højde", 
							"Armlæn", 
							"Auto. nødbremse", 
							"Auto parkering", 
							"Auto start/stop", 
							"Automatisk lys", 
							"AUX tilslutning", 
							"Bakkamera", 
							"Bakspejl m. nedbl.", 
							"Bi-xenon", 
							"Blindvinkelassistent", 
							"Bluetooth", 
							"Brugtbilsattest", 
							"Centrallås fjernb.", 
							"Dab radio", 
							"Dæktryksmåler", 
							"Digitalt cockpit", 
							"El inst. førersæde m. memory", 
							"Elektrisk kabinevarmer", 
							"Elektrisk parkeringsbremse", 
							"Elektrisk komfortsæder", 
							"Elektriskbagklap", 
							"El-klapbare sidespejle m. varme", 
							"Elruder, 4x", 
							"Fartpilot", 
							"Fartpilot adaptiv", 
							"Fjernlysassistent", 
							"Fuld LED forlygter", 
							"Head-up display", 
							"Infocenter", 
							"Internet", 
							"Isofix", 
							"Klimaanlæg, 4-zonet", 
							"Kørecomputer", 
							"Kurvelys", 
							"Læderrat", 
							"LED kørelys", 
							"Lygtevasker", 
							"Musik via bluetooth", 
							"Navigation", 
							"Nøglefri betjening", 
							"Panoramatag", 
							"Parkeringssensor (bag)", 
							"Parkeringssensor (for)", 
							"Regnsensor", 
							"Sædebetræk, dellæder", 
							"Sædebetræk, læder", 
							"Sædevarme", 
							"SD kortlæser", 
							"Service ok", 
							"Servo", 
							"Skiltegenkendelse", 
							"Soltag, elektrisk", 
							"Soltag, manuelt", 
							"Splitbagsæde", 
							"Sportssæder", 
							"Startspærre", 
							"Svingbart træk (elektrisk)", 
							"Svingbart træk (manuelt", 
							"Tågelygter", 
							"Tagræling", 
							"Trådløs mobilopladning", 
							"Træthedsregistrering", 
							"Undervogn sænket", 
							"USB tilslutning", 
							"Vognbaneassistent", 
							"Xenonlygter",
						];
							
							
?>