

<script>

    let gender: [
        nominative: {
            neutral: 'they',
                masculine: 'he',
                feminine: 'she',
                elverson: 'ey',
                spivak: 'E',
                humanist: 'hu',
                peh: 'peh',
                per: 'per',
                thon: 'thon',
                jee: 'jee',
                ve: 've',
                xe: 'xe',
                zir: 'ze',
                hir: 'ze',
                mer: 'ze',
                zhe: 'zhe',
        },
        accusative: {
            neutral: 'them',
                masculine: 'him',
                feminine: 'her',
                elverson: 'em',
                spivak: 'Em',
                humanist: 'hum',
                peh: 'pehm',
                per: 'per',
                thon: 'thon',
                jee: 'jem',
                ve: 'ver',
                xe: 'xem',
                zir: 'zem',
                hir: 'hir',
                mer: 'mer',
                zhe: 'zhim',
        },
        reflexive: {
            neutral: 'themself',
                masculine: 'himself',
                feminine: 'herself',
                elverson: 'eirself',
                spivak: 'Emself',
                humanist: 'humself',
                peh: 'pehself',
                per: 'perself',
                thon: 'thonself',
                jee: 'jemself',
                ve: 'verself',
                xe: 'xemself',
                zir: 'zirself',
                hir: 'hirself',
                mer: 'zemself',
                zhe: 'zhimself',
        },
        possessive: {
            pronominal: {
                neutral: 'their',
                    masculine: 'his',
                    feminine: 'her',
                    elverson: 'eir',
                    spivak: 'Eir',
                    humanist: 'hus',
                    peh: 'peh\'s',
                    per: 'per',
                    thon: 'thons',
                    jee: 'jeir',
                    ve: 'vis',
                    xe: 'xyr',
                    zir: 'zes',
                    hir: 'hir',
                    mer: 'zer',
                    zhe: 'zher',
            },
            predicative: {
                neutral: 'theirs',
                    masculine: 'his',
                    feminine: 'hers',
                    elverson: 'eirs',
                    spivak: 'Eirs',
                    humanist: 'hus',
                    peh: 'peh\'s',
                    per: 'pers',
                    thon: 'thons',
                    jee: 'jeirs',
                    ve: 'vis',
                    xe: 'xyrs',
                    zir: 'zes',
                    hir: 'hirs',
                    mer: 'zers',
                    zhe: 'zhers',
            },
        },
    ]


</script>