<script>

	var gogTheLink;
	var gogTheCarModel;
	var gogTheEngine;
	var gogThePrice;
	var gogHorsePowerAndNm;
	var gogFromZeroToHundred;
	var gogTheTopSpeed;
	var gogEnergyToUse;
	var gogEnergyUsage;
	var gogTheEuronorm;
	var gogTheWidth;
	var gogTheLength;
	var gogTheHeight;
	var gogLoadAbility;
	var gogDrivingWheels;
	var gogTheCylinders;
	var gogAbsBreaks;
	var gogTheMaxLoad;
	var gogNumberOfAirbags;
	var gogDoesEsp;
	var gogTheGasTank;
	var gogTheGears;
	var gogTheGearType;
	var gogTheWeight;
	var gogCountOfDoors;
	var gogTheRegistrationDate;
	var gogTheProductionDate;
	var gogYearOfTheModel;
	var gogLastDateOfSight;
	var gogTheColor;
	var gogTowbar;
	var gogAlloyWheels;
	var gogAutoAndroid;
	var gogTowbarDetachable;
	var gogAntispin;
	var gogCarplayApple;
	var gogArmRelax;
	var gogAutoEmergencyBreak;
	var gogAutoParking;
	var gogAutoStartStop;
	//var gogAutoGear;
	var gogAutoLight;
	var gogAuxAdding;
	var gogRearCamera;
	var gogRearMirrorLessLight;
	var gogBiXenon;
	var gogBlindAngelassistent;
	var gogBluetooth;
	var gogUsedCarAttest;
	var gogCentralLockRemote;
	var gogDabRadio;
	var gogwheelAirMeassure;
	var gogCockpitDigital;
	var gogFrontseatElInstall;
	var gogCabinWarmEl;
	var gogParkingBreakEl;
	var gogElectricComfortableSeats;
	var gogElectricBackDoor;
	var gogElectricSideMirrorWarm;
	var gogElectricWindowsTimesFour;
	var gogSpeedPilot;
	var gogSpeedPilotAdaptive;
	var gogRemoteLightAssistant;
	var gogCompleteLedFrontLight;
	var gogHeadUpDisplay;
	var gogInfoCenter;
	var gogInternet;
	var gogIsofix;
	var gogClimateCenterFourZone;
	var gogDrivingComputer;
	var gogCurvingLight;
	var gogLeatherWheel;
	var gogLedDrivingLight;
	var gogLightWashers;
	var gogMusicViaBluetooth;
	var gogNavigation;
	var gogKeylessOperation;
	var gogPanoramaRoof;
	var gogParkingSensorBack;
	var gogParkingSensorFront;
	var gogRainSensor;
	var gogSeatCoversPartlyLeather;
	var gogSeatCoverLeather;
	var gogSeatWarming;
	var gogSdMapReader;
	var gogOkService;
	var gogServo;
	var gogSignRecognition;
	var gogSunRoofElectric;
	var gogSunRoofManual;
	var gogBackSeatSplit;
	var gogSportSeats;
	var gogStartingLight;
	var gogPivotableTractionElectric;
	var gogPivotableTractionManual;
	var gogFogLights;
	var gogRoofRails;
	var gogwirelessMobileRecharge;
	var gogRegistrationOfTired;
	var gogUnderCarLowered;
	var gogUsbConnection;
	var gogLaneAssistant;
	var gogxenonLights;
	var gogContactInfo;
	var gogTheKilometers;

	function setTheFirstGogArray(gogCarArray)
	{
		gogCarArray.push(gogTheLink);
		gogCarArray.push(gogContactInfo);
		gogCarArray.push(gogTheCarModel);
		gogCarArray.push(gogTheEngine);
		gogCarArray.push(gogThePrice);
		gogCarArray.push(gogTheKilometers);
		gogCarArray.push(gogHorsePowerAndNm);
		gogCarArray.push(gogTheRegistrationDate);
		gogCarArray.push(gogTheGearType);
		gogCarArray.push(gogFromZeroToHundred);
		gogCarArray.push(gogTheTopSpeed);
		gogCarArray.push(gogEnergyToUse);
		gogCarArray.push(gogEnergyUsage);
		gogCarArray.push(gogLoadAbility);
		gogCarArray.push(gogDrivingWheels);
		gogCarArray.push(gogTheCylinders);
		gogCarArray.push(gogAbsBreaks);
		gogCarArray.push(gogTheMaxLoad);
		gogCarArray.push(gogNumberOfAirbags);
		gogCarArray.push(gogDoesEsp);
		gogCarArray.push(gogTheGasTank);
		gogCarArray.push(gogTheGears);
		gogCarArray.push(gogTheWeight);
		gogCarArray.push(gogCountOfDoors);
		gogCarArray.push(gogTheProductionDate);
		gogCarArray.push(gogYearOfTheModel);
		gogCarArray.push(gogLastDateOfSight);
		gogCarArray.push(gogTheColor);
		gogCarArray.push(gogAlloyWheels);
		gogCarArray.push(gogAutoAndroid);
		gogCarArray.push(gogTowbar);
		gogCarArray.push(gogTowbarDetachable);
		gogCarArray.push(gogAntispin);
		gogCarArray.push(gogCarplayApple);
		gogCarArray.push(gogTheEuronorm);
		gogCarArray.push(gogTheWidth);
		gogCarArray.push(gogTheLength);
		gogCarArray.push(gogTheHeight);
		gogCarArray.push(gogArmRelax);
		gogCarArray.push(gogAutoEmergencyBreak);
		gogCarArray.push(gogAutoParking);
		gogCarArray.push(gogAutoStartStop);
		//gogCarArray.push(gogAutoGear);
		gogCarArray.push(gogAutoLight);
		gogCarArray.push(gogAuxAdding);
		gogCarArray.push(gogRearCamera);
		gogCarArray.push(gogRearMirrorLessLight);
		gogCarArray.push(gogBiXenon);
		gogCarArray.push(gogBlindAngelassistent);
		gogCarArray.push(gogBluetooth);
		gogCarArray.push(gogUsedCarAttest);
		gogCarArray.push(gogCentralLockRemote);
		gogCarArray.push(gogDabRadio);
		gogCarArray.push(gogwheelAirMeassure);
		gogCarArray.push(gogCockpitDigital);
		gogCarArray.push(gogFrontseatElInstall);
		gogCarArray.push(gogCabinWarmEl);
		gogCarArray.push(gogParkingBreakEl);
		gogCarArray.push(gogElectricComfortableSeats);
		gogCarArray.push(gogElectricBackDoor);
		gogCarArray.push(gogElectricSideMirrorWarm);
		gogCarArray.push(gogElectricWindowsTimesFour);
		gogCarArray.push(gogSpeedPilot);
		gogCarArray.push(gogSpeedPilotAdaptive);
		gogCarArray.push(gogRemoteLightAssistant);
		gogCarArray.push(gogCompleteLedFrontLight);
		gogCarArray.push(gogHeadUpDisplay);
		gogCarArray.push(gogInfoCenter);
		gogCarArray.push(gogInternet);
		gogCarArray.push(gogIsofix);
		gogCarArray.push(gogClimateCenterFourZone);
		gogCarArray.push(gogDrivingComputer);
		gogCarArray.push(gogCurvingLight);
		gogCarArray.push(gogLeatherWheel);
		gogCarArray.push(gogLedDrivingLight);
		gogCarArray.push(gogLightWashers);
		gogCarArray.push(gogMusicViaBluetooth);
		gogCarArray.push(gogNavigation);
		gogCarArray.push(gogKeylessOperation);
		gogCarArray.push(gogPanoramaRoof);
		gogCarArray.push(gogParkingSensorBack);
		gogCarArray.push(gogParkingSensorFront);
		gogCarArray.push(gogRainSensor);
		gogCarArray.push(gogSeatCoversPartlyLeather);
		gogCarArray.push(gogSeatCoverLeather);
		gogCarArray.push(gogSeatWarming);
		gogCarArray.push(gogSdMapReader);
		gogCarArray.push(gogOkService);
		gogCarArray.push(gogServo);
		gogCarArray.push(gogSignRecognition);
		gogCarArray.push(gogSunRoofElectric);
		gogCarArray.push(gogSunRoofManual);
		gogCarArray.push(gogBackSeatSplit);
		gogCarArray.push(gogSportSeats);
		gogCarArray.push(gogStartingLight);
		gogCarArray.push(gogPivotableTractionElectric);
		gogCarArray.push(gogPivotableTractionManual);
		gogCarArray.push(gogFogLights);
		gogCarArray.push(gogRoofRails);
		gogCarArray.push(gogwirelessMobileRecharge);
		gogCarArray.push(gogRegistrationOfTired);
		gogCarArray.push(gogUnderCarLowered);
		gogCarArray.push(gogUsbConnection);
		gogCarArray.push(gogLaneAssistant);
		gogCarArray.push(gogxenonLights);
		
		//console.log("pushing to dataarray");
		carModel = gogCarArray[1];
		engine = gogCarArray[2];
		price = gogCarArray[3];
		//if(carModel != "-" && engine != "-" && price != "-") {
			//console.log("pushing to dataarray");
			dataArray.push(gogCarArray);
		//}
	}


</script>