<script>

	var gogTheLink;
	var gogTheCarModel;
	var gogTheEngine;
	var gogThePrice;
	var gogHorsePowerAndNm;
	var gogFromZeroToHundred;
	var gogTheTopSpeed;
	var gogEnergyToUse;
	var gogEnergyUsage;
	var gogTheEuronorm;
	var gogTheWidth;
	var gogTheLength;
	var gogTheHeight;
	var gogLoadAbility;
	var gogDrivingWheels;
	var gogTheCylinders;
	var gogAbsBreaks;
	var gogTheMaxLoad;
	var gogNumberOfAirbags;
	var gogDoesEsp;
	var gogTheGasTank;
	var gogTheGears;
	var gogTheGearType;
	var gogTheWeight;
	var gogCountOfDoors;
	var gogTheRegistrationDate;
	var gogTheProductionDate;
	var gogYearOfTheModel;
	var gogLastDateOfSight;
	var gogTheColor;
	var gogTowbar;
	var gogAlloyWheels;
	var gogAutoAndroid;
	var gogTowbarDetachable;
	var gogAntispin;
	var gogCarplayApple;
	var gogArmRelax;
	var gogAutoEmergencyBreak;
	var gogAutoParking;
	var gogAutoStartStop;
	//var gogAutoGear;
	var gogAutoLight;
	var gogAuxAdding;
	var gogRearCamera;
	var gogRearMirrorLessLight;
	var gogBiXenon;
	var gogBlindAngelassistent;
	var gogBluetooth;
	var gogUsedCarAttest;
	var gogCentralLockRemote;
	var gogDabRadio;
	var gogwheelAirMeassure;
	var gogCockpitDigital;
	var gogFrontseatElInstall;
	var gogCabinWarmEl;
	var gogParkingBreakEl;
	var gogElectricComfortableSeats;
	var gogElectricBackDoor;
	var gogElectricSideMirrorWarm;
	var gogElectricWindowsTimesFour;
	var gogSpeedPilot;
	var gogSpeedPilotAdaptive;
	var gogRemoteLightAssistant;
	var gogCompleteLedFrontLight;
	var gogHeadUpDisplay;
	var gogInfoCenter;
	var gogInternet;
	var gogIsofix;
	var gogClimateCenterFourZone;
	var gogDrivingComputer;
	var gogCurvingLight;
	var gogLeatherWheel;
	var gogLedDrivingLight;
	var gogLightWashers;
	var gogMusicViaBluetooth;
	var gogNavigation;
	var gogKeylessOperation;
	var gogPanoramaRoof;
	var gogParkingSensorBack;
	var gogParkingSensorFront;
	var gogRainSensor;
	var gogSeatCoversPartlyLeather;
	var gogSeatCoverLeather;
	var gogSeatWarming;
	var gogSdMapReader;
	var gogOkService;
	var gogServo;
	var gogSignRecognition;
	var gogSunRoofElectric;
	var gogSunRoofManual;
	var gogBackSeatSplit;
	var gogSportSeats;
	var gogStartingLight;
	var gogPivotableTractionElectric;
	var gogPivotableTractionManual;
	var gogFogLights;
	var gogRoofRails;
	var gogwirelessMobileRecharge;
	var gogRegistrationOfTired;
	var gogUnderCarLowered;
	var gogUsbConnection;
	var gogLaneAssistant;
	var gogxenonLights;
	var gogContactInfo;

	function setTheFirstGogArray(singleCarArray)
	{
		singleCarArray.push(gogContactInfo);
		singleCarArray.push(gogTheLink);
		singleCarArray.push(gogTheCarModel);
		singleCarArray.push(gogTheEngine);
		singleCarArray.push(gogHorsePowerAndNm);
		singleCarArray.push(gogThePrice);
		singleCarArray.push(gogFromZeroToHundred);
		singleCarArray.push(gogTheTopSpeed);
		singleCarArray.push(gogEnergyToUse);
		singleCarArray.push(gogEnergyUsage);
		singleCarArray.push(gogTheEuronorm);
		singleCarArray.push(gogTheWidth);
		singleCarArray.push(gogTheLength);
		singleCarArray.push(gogTheHeight);
		singleCarArray.push(gogLoadAbility);
		singleCarArray.push(gogDrivingWheels);
		singleCarArray.push(gogTheCylinders);
		singleCarArray.push(gogAbsBreaks);
		singleCarArray.push(gogTheMaxLoad);
		singleCarArray.push(gogNumberOfAirbags);
		singleCarArray.push(gogDoesEsp);
		singleCarArray.push(gogTheGasTank);
		singleCarArray.push(gogTheGears);
		singleCarArray.push(gogTheGearType);
		singleCarArray.push(gogTheWeight);
		singleCarArray.push(gogCountOfDoors);
		singleCarArray.push(gogTheRegistrationDate);
		singleCarArray.push(gogTheProductionDate);
		singleCarArray.push(gogyearOfTheModel);
		singleCarArray.push(gogLastDateOfSight);
		singleCarArray.push(gogTheColor);
		singleCarArray.push(gogAlloyWheels);
		singleCarArray.push(gogAutoAndroid);
		singleCarArray.push(gogTowbar);
		singleCarArray.push(gogTowbarDetachable);
		singleCarArray.push(gogAntispin);
		singleCarArray.push(gogCarplayApple);
		singleCarArray.push(gogArmRelax);
		singleCarArray.push(gogAutoEmergencyBreak);
		singleCarArray.push(gogAutoParking);
		singleCarArray.push(gogAutoStartStop);
		//singleCarArray.push(gogAutoGear);
		singleCarArray.push(gogAutoLight);
		singleCarArray.push(gogAuxAdding);
		singleCarArray.push(gogRearCamera);
		singleCarArray.push(gogRearMirrorLessLight);
		singleCarArray.push(gogBiXenon);
		singleCarArray.push(gogBlindAngelassistent);
		singleCarArray.push(gogBluetooth);
		singleCarArray.push(gogUsedCarAttest);
		singleCarArray.push(gogCentralLockRemote);
		singleCarArray.push(gogDabRadio);
		singleCarArray.push(gogwheelAirMeassure);
		singleCarArray.push(gogCockpitDigital);
		singleCarArray.push(gogFrontseatElInstall);
		singleCarArray.push(gogCabinWarmEl);
		singleCarArray.push(gogParkingBreakEl);
		singleCarArray.push(gogElectricComfortableSeats);
		singleCarArray.push(gogElectricBackDoor);
		singleCarArray.push(gogElectricSideMirrorWarm);
		singleCarArray.push(gogElectricWindowsTimesFour);
		singleCarArray.push(gogSpeedPilot);
		singleCarArray.push(gogSpeedPilotAdaptive);
		singleCarArray.push(gogRemoteLightAssistant);
		singleCarArray.push(gogCompleteLedFrontLight);
		singleCarArray.push(gogHeadUpDisplay);
		singleCarArray.push(gogInfoCenter);
		singleCarArray.push(gogInternet);
		singleCarArray.push(gogIsofix);
		singleCarArray.push(gogClimateCenterFourZone);
		singleCarArray.push(gogDrivingComputer);
		singleCarArray.push(gogCurvingLight);
		singleCarArray.push(gogLeatherWheel);
		singleCarArray.push(gogLedDrivingLight);
		singleCarArray.push(gogLightWashers);
		singleCarArray.push(gogMusicViaBluetooth);
		singleCarArray.push(gogNavigation);
		singleCarArray.push(gogKeylessOperation);
		singleCarArray.push(gogPanoramaRoof);
		singleCarArray.push(gogParkingSensorBack);
		singleCarArray.push(gogParkingSensorFront);
		singleCarArray.push(gogRainSensor);
		singleCarArray.push(gogSeatCoversPartlyLeather);
		singleCarArray.push(gogSeatCoverLeather);
		singleCarArray.push(gogSeatWarming);
		singleCarArray.push(gogSdMapReader);
		singleCarArray.push(gogOkService);
		singleCarArray.push(gogServo);
		singleCarArray.push(gogSignRecognition);
		singleCarArray.push(gogSunRoofElectric);
		singleCarArray.push(gogSunRoofManual);
		singleCarArray.push(gogBackSeatSplit);
		singleCarArray.push(gogSportSeats);
		singleCarArray.push(gogStartingLight);
		singleCarArray.push(gogPivotableTractionElectric);
		singleCarArray.push(gogPivotableTractionManual);
		singleCarArray.push(gogFogLights);
		singleCarArray.push(gogRoofRails);
		singleCarArray.push(gogwirelessMobileRecharge);
		singleCarArray.push(gogRegistrationOfTired);
		singleCarArray.push(gogUnderCarLowered);
		singleCarArray.push(gogUsbConnection);
		singleCarArray.push(gogLaneAssistant);
		singleCarArray.push(gogxenonLights);
		
		//console.log("pushing to dataarray");
		carModel = singleCarArray[1];
		engine = singleCarArray[2];
		price = singleCarArray[3];
		if(carModel != "-" && engine != "-" && price != "-") {
			dataArray.push(gogSingleCarArray);
		}
	}


</script>