
<?php

    return
        [
            'frontpage' => [
                'tab' => 'Cv',
                'cv' => 'Curriculum Vitae',
                'adr' => 'Address:',
                'adrTxt' => 'Bronzealdervej 64A, 8210 Aarhus V',
                'nameHeader' => 'Name:',
                'name' => 'By Lars Søndertoft Nielsen',
                'back' => 'Back to homepage',
                'educationBubble' => 'Here you will find a better description of my education. What I have focused on etc ',
                'edu' => 'Education',
                'sparetimeBubble' => 'Here you will find a better description of what I do in my spare time and what else I spend my time on',
                'sparetimeHeader' => 'Hobbies',
                'qualBubble' => 'Here you will find a better description of what minor educations and certifications I have taken over time',
                'qualHeader' => 'Qualifications',
                'langBubble' => 'Here is a little elaboration of where my level is and how much I practice the different languages',
                'langHeader' => 'Language',
                'otherBubble' => 'Click here to see a more detailed description of what I have done over time',
                'otherHeader' => 'Through time',
                'contactHeader' => 'Contact:',
                'phoneNr' => '23309696:',
                'webMail' => 'lars.sondertoft@gmail.com',
                'workRelation' => 'WorkRelation',
                'theJob' => 'Job:',
                'mailLink' => 'Email',
                'pdfCv' => 'CV - pdf',
                'theWork' => 'IT Developer',
                'linkedIn' => 'LinkedIn',
                'flexWork' => 'Flexyder'
            ],
            'general' => [
                'masterProof' => 'Candidate proof:',
                'gradProof' => 'Bachelor proof:',
                'gymProof' => 'Gym Proof:',
                'gymSubjects' => 'My field of study in high school was: Music A, Mathematics A, Chemistry B',
                'gradHeader' => 'Bachelor of Computer Science',
                'docProof' => 'Proof',
                'pubSchool' => 'Lemtorpskolen Lemvig',
                'masterSchool' => 'Master of Computer Science',
                'gradSchool' => 'Bachelor of Computer Science',
                'gymSchool' => 'Lemvig Gymnasium',
                'au' => 'Aarhus University',
                '14-16' => '2014 - 2016',
                '11-14' => '2011 - 2014',
                '10-11' => '2010 - 2011',
                '07-10' => '2007 - 2010',
                '06-07' => '2006 - 2007',
                'masterSpecial' => 'Specialization in cryptological protocol theory',
                'gradSpecial' => 'Wrote a compiler under the thesis',
                'gradElective' => 'Two electives in mathematics',
                'gymLine' => 'Music student',
                'gymSubject' => 'Music A, Math A, Chemistry B',
                'weightLift' => 'Weightlift',
                '02/02-2019' => 'BDM 2.februar 2019',
                '19/08-2019' => 'BDM-Vest 19.august 2019, bronze medal',
                'highSchool' => 'Aalborg Sportshøjskole',
                '2011' => '2011',
                '2010' => '2010',
                'crossJoin' => 'Crossfit',
                'crossJoinPlaces' => 'Aarhus crossfit, Copenhagen crossfit',
                'crossJoinTime' => 'Throughout my time at university',
                'eng' => 'English',
                'langFloat' => 'Floating',
                'workHeader' => 'Work',
                'piipl' => 'Piipl, 2017-2018',
                'bizsys' => 'Bizsys, 2019-2020',
                'saxHeader' => 'Saxophone',
                'barSax' => 'baritone saxophone',
                'altSax' => 'Alt saxophone',
                'saxPlay' => 'Saxophone Quartet, Orchestra',
                'miliHeader' => 'The Royal Life Guards',
                'miliJob' => 'Tambour - marchtromme',
                'ger' => 'German',
                'gerLevel' => 'Elemental Level',
                'courseraHeader' => 'Coursera.org',
                'courseraMath' => 'Introduction to Mathematical thinking',
                'courseraLogic' => 'How to reason and argue',
                'itHeader' => 'Programming',
                'itWeb' => 'Web Programming',
                'itLang' => 'PHP, jquery, javascript, css, html',
                'itGit' => 'Github, Git Desktop',
                'afterSchoolHeader' => 'Venø efterskole',
                'afterSchoolLine' => 'Nature and outdoor life',
                'fra' => 'French',
                'spa' => 'Spanish',
                'comHeader' => 'Computer Games',
                'comBliz' => 'Blizzard',
                'comGames' => 'Overwatch, Heroes of the Storm',
                'inoHeader' => 'Entrepreneurial course',
                'inoProof' => 'Entrepreneurial evidence:',
                'jekaHeader' => 'Local Fish Factory',
                'jekaFish' => 'Jeka Fisk',
                'jekaWork' => 'Office work and production',
                'pdfCv' => 'My CV in pdf format:',
                'pubProof' => 'Primary school proof:',
                'back' => 'Back',
                'backCv' => 'Back to CV',
                'cvEdu' => 'CV - education',
                'author' => 'Af Lars Søndertoft Nielsen',
                'masterHeader' => 'I wrote my thesis in cryptological protocol theory.
                A subject that lies in the Crypto group in computer science at Aarhus University. ',
                'masterTxtOne' => 'The thesis was based on an interactive sigma protocol and its properties.
                                    A sigma protocol is a protocol between a client and a server. The idea then is that the client must prove
                                    that he is who he is using a unique knowledge.
                                    He must prove to the server that he has the unique knowledge, without showing that knowledge.
                                    Otherwise it will not be unique anymore. ',
                'masterTxtTwo' => 'Then there was a review of two different transformations of the interactive sigma protocol into a non-interactive
                                    protocol. That way you can have the protocol with you, to deliver it to a server,
                                    which can verify that it has been barked correctly. ',
                'masterTxtThree' => 'Finally, the two transformations were compared, with a view to the differences and their applications.',
                'gradTxt' => 'The thesis of the bachelor\'s program at the time was to write a compiler.
It was like that for all computer science students. ',
                'gradTxtTwo' => 'A compiler is the program that roughly translates, for example, the java or python code you have written,
                                to machine code. If you are interested, you can read more here: ',
                'com' => 'Compiler',
            ],
            'otherPage' => [
                'cv' => 'CV - through time',
                'header' => 'Through time',
                'workTime' => 'Work',
                'sparetimeBox' => 'Leisure',
                'piipl' => 'Piipl',
                'piiplWork' => 'IT Developer, 2017-2018',
                'workLink' => 'Link',
                'piiplTxt' => 'It was while working here that I was investigated in',
                'piiplTxtTwo' => 'to find out if I should be flexyder or not',
                'mathHeader' => 'Introduction to Mathematical thinking',
                'mathTxt' => 'A small course where you learn about it in general',
                'mathTxtTwo' => 'mathematical thinking',
                'courLink' => 'Link to coursera',
                'bizHeader' => 'Bizsys',
                'bizWork' => 'IT Developer, 2019-2020',
                'statement' => 'Statement from my then colleague Shahram',
                'logicHeader' => 'How to reason and argue',
                'logicTxt' => 'A small course where you learn the basics',
                'logicTxtTwo' => 'to argue and reason',
                'logicLink' => 'Link to coursera',
                'jekaLocal' => 'Local Fish Factory',
                'jekaHeader' => 'Jeka Fish',
                'jekaWork' => 'Production work',
                'jekaWorkTwo' => 'Office work',
                'crossTime' => 'Throughout my time at university',
                'crossAu' => 'Aarhus Crossfit',
                'crossCph' => 'Copenhagen Crossfit',
                'paperHeader' => 'Avisbud',
                'paperWork' => 'Local newspaper',
                'paperWorkTwo' => 'Jyllandsposten',
                'runHeader' => 'Run',
                'runTime' => 'Throughout my life',
                'runEvent' => 'Lemvig Byløb',
                'swimHeader' => 'Swim',
                'swimClub' => 'Lemvig Svømmeklub',
                'swimWork' => 'Instructor for a year',
                'scoutHeader' => 'Scout',
                'scoutType' => 'DDS',
                'scoutClub' => 'Thøger Larsen Gruppen Lemvig',
                'grassHeader' => 'Mow grass',
                'grassWork' => 'On own land, next door',
                'grassWorkTwo' => 'For the landowners\' association',
                                       'basketHeader' => 'Basketball',
                'basketClub' => 'Lemvig Basket',
                'basketEvent' => 'Limfjordscup',
                'courseProof' => 'Course Proof:',
                'argueName' => 'Think again: How to reason and argue',
                'argueTxt' => 'This course is about reasoning and arguing.

                                        You learn simple but vital rules to follow when considering any topic
                                        and comes around common and tempting mistakes that one must avoid when one wants to argue his case.
                                        one learnr how to identify, analyze and evaluate arguments from other people
                                        and how to construct own arguments. ',
                'stateHeader' => 'Statement by Shahram:',
                'courseProof' => 'Course Proof:',
                'mathHeader' => 'Introduction to mathematical thinking',
                'mathDescription' => 'Mathematical thinking is not the same as doing mathematics - at least not,
                                as mathematics is typically presented in our school system.
                                School mathematics typically focuses on learning procedures to solve very stereotypical problems.
                                Professional mathematicians think in a certain way to solve real problems, problems,
                                that can arise from the everyday world, or from science, or from mathematics itself.
                                The key to success in school math is learning to think inside the box.
                                In contrast, an important feature of mathematical thinking outside the box is a valuable ability in today\'s world.
This course helps to develop the crucial mindset. ',
                ],
            'sparetimePage' => [
                'weightEvent' => 'BDM February 2, 2019',
                'weightEventTwo' => 'BDM-Vest 19 August 2019, bronze medal',
                'saxQuartet' => 'Saxophone Quartet',
                'polHeader' => 'Politics',
                'polFollow' => 'Following the political situation',
                'polDiscuss' => 'Please discuss',
                'hisHeader' => 'History',
                'hisDates' => 'Year',
                'hisEvent' => 'Events through time',
                'sptHeader' => 'CV - leisure',
                'flexHeader' => 'Flexyder',
                'flexTxt' => 'I unfortunately became a flexyder because I hit my head as an eight-year-old in a traffic accident
                                        Have added a picture where you can see the scar I got after the accident:
                                        Unfortunately, this has had the consequence that I have a harder time concentrating.
                                        If I encounter a task I have not seen before, I must have plenty of time to get into it and understand it.
But if I get the long time, I have the opportunity to be really good inside
                                        exactly what I work with.
The picture is taken where I am cut in the military, why I smile. ',

            ],
            'errorMess' => 'Your browser does not support the video tag.',
            'eventHeader' => 'Here is an excerpt from a convention on August 19, 2019',
            'liftTxt' => 'I started weightlifting when I finished my studies
                        In the short time I have been doing weightlifting, I have participated in two rallies.
I got a bronze medal at the event that the video is from. ',
            'itHeader' => 'It',
            'itWork' => 'IT Development and Programming',
            'itTxt' => 'Here\'s a little about what I\'ve done and am still working on as an IT developer
I have worked mostly with web development. It includes some of the following: ',
            'php' => 'Php',
            'py' => 'Python',
            'html' => 'Html',
            'css' => 'Css',
            'js' => 'Jquery / javascript',
            'itTools' => 'Used the following tools over time',
            'phpS' => 'Php Storm',
            'np ++' => 'Notepad ++',
            'dj' => 'Django',
            'git' => 'Git',
            'gitD' => 'Git Desktop',
            'qual' => [
                'cvHeader' => 'CV Qualifications',
                'qual' => 'Qualifications',
                'climbProof' => 'Climb proof:',
                'fireCourse' => 'Firebrand Course',
                'fireProof' => 'Firebrand proof:',
                'navDev' => 'Navision Developer',
                'navTxt' => 'I took this course when I was employed as a Navision developer for a very short period of time',
                '16' => '16',
                'micNav' => 'Microsoft Navision',
                'fireLocation' => 'Scania in Sweden',
                'highSchoolProof' => 'High School Proof',
                'link' => 'Link',
                'hsTxt' => 'to the college where I was on the crossfit line.',
                'miliProof' => 'Military proof:',
                'miliNote' => 'Note:',
                'miliTxt' => 'I was not on call as stated on the paper. I was a tambour and played the march drum. ',
            ]
        ];


?>