<?php
	return
	[
		'general' =>
		[
			'tabHeader' => 'Diesel',
			'date' => 'Date',
			'back' => 'Back',
			'tab' => 'Advanced',
		],
		'frontpage' =>
		[
			'header' => 'Diesel page',
			'infoHeader' => 'Enter your numbers below and they will be shown in the table to the right',
			'km' => 'Number of kilometers',
			'liter' => 'Liter',
			'kr' => 'Kroner',
			'enterNumbers' => 'Enter Numbers',
			'tableHeader' => 'Table of entered diesel numbers',
			'deleteRow' => 'Delete row',
			'confirmDelete' => 'Are you sure you want to delete this row?',
			'yes' => 'Yes',
			'no' => 'No',
			'backButton' => 'Back to homepage',
		],
		'dataTable' =>
		[
			'km' => 'Km',
			'liter' => 'Liter',
			'kr' => 'Kroner',
			'kr/l' => 'Kr/L',
			'km/l' => 'Km/L',
			'km/kr' => 'Km/Kr',
			'km/kr' => 'Km/Kr',
			'kr/km' => 'Kr/Km',
			'l/km' => 'L/Km',
			'l/kr' => 'L/Kr',
		],
		'carPage' =>
		[
			'header' => 'My car',
			'carAttributes' => 'Car attributes:',
			'type' => 'Art',
			'carType' => 'Car',
			'seatNumber' => 'Number of seats incl. leads: ',
			'seatValue' => '1/5',
			'standNumber' => 'Number of stands:',
			'standValue' => '0',
			'useIndex' => 'Usage:',
			'useValue' => 'Private Passenger:',
			'driveForce' => 'Drive Force:',
			'diesel' => 'Diesel',
			'weightTxt' => 'Ready weight:',
			'weightValue' => '1102kg',
			'gasTxt' => 'Fuel consumption:',
			'gasValue' => '25 km / l ',
			'axesNumber' => 'Number of axes:',
			'axesValue' => '2',
			'kwTxt' => 'Maximum power (kW):',
			'kwValue' => '50, 0 ',
			'carModel' => 'Peugeot 206+',
			'backButton' => 'Back',
		],
		'statButtons' =>
		[
			'statistic' => 'Click here to see more advanced statistics',
			'theCar' => 'Click here to see which car it\'s about',
		],
		'advButs' =>
		[
			'backButton' => 'Back',
			'dateStats' => 'Date Stats',
			'kmStats' => 'Statistics for km',
			'literStats' => 'Statistics for liters',
			'krStats' => 'Statistics for kr',
			'krlStats' => 'Statistics for kr/l',
			'kmlStats' => 'Statistics for km/l',
			'kmKrStats' => 'Statistics for km/kr',
			'customStats' => 'Create your own graph',
		],
		'stats' =>
		[
			'header' => 'Advanced statistics for diesel consumption',
			'literHeader' => 'Advanced statistics for number of liters',
			'krlHeader' => 'Advanced statistics for kroner per liter',
			'kmlHeader' => 'Advanced statistics for kilometers per liter',
			'krHeader' => 'Advanced statistics for number of kroner',
			'kmkrHeader' => 'Advanced statistics for kilometers per kroner',
			'kmHeader' => 'Advanced mileage statistics',
			'dateHeader' => 'Advanced Date Statistics',
			'lkr' => 'liter/kroner',
			'lkm' => 'liter/kilometer',
			'krkm' => 'Kroner/kilometer',
			'krl' => 'Kroner / liter',
			'kml' => 'Kilometer / liter',
			'kmKr' => 'Kilometer / kroner',
			'stdev' => 'Default Deviation',
			'km' => 'Kilometer',
			'liter' => 'Liter',
			'kr' => 'Kroner',
			'sum' => 'sum',
		],
		'graphs' =>
		[
			'dateHeader' => 'Date Frequency',
			'literHeader' => 'Frequency chart of liters',
			'krlHeader' => 'Frequency chart of kroner per liter',
			'krHeader' => 'Frequency chart of kroner',
			'kmlHeader' => 'Frequency chart over kilometers per liter',
			'kmkrHeader' => 'Frequency chart over kilometers per kroner',
			'kmHeader' => 'Frequency chart over kilometers',
			'freqX' => 'Percent',
			'freqY' => 'Year',
			'literY' => 'Liter interval',
			'krlY' => 'DKK per liter interval',
			'krY' => 'Liter interval',
			'kmlY' => 'Kilometers per liter interval',
			'kmkrY' => 'Kilometer per kroner interval',
			'kmY' => 'Mileage interval',
			'dieselHeader' => 'Diesel Accounts',
			'threeHeader' => 'L/km, l/kr and kr/km',
			'literStdVar' => 'Liter - standard deviation and variance',
			'krlStdVar' => 'NOK per liter - standard deviation and variance',
			'krStdVar' => 'Kroner - standard deviation and variance',
			'kmlStdVar' => 'Kilometers per liter - standard deviation and variance',
			'kmkrStdVar' => 'Kilometers per kroner - standard deviation and variance',
			'kmStdVar' => 'Kilometer - standard deviation and variance',
			'stdev' => 'Default Deviation',
			'averVar' => 'Average, variance',
		],
		'dropdown' =>
		[
			'header' => 'Setup your own graph by selecting from the fields at the bottom of the page',
			'short' => 'Short explanation',
			'explanation' => 'St dev stands for standard deviation, which translated is standard deviation. That value is an expression
			for how much all the values ​​are distributed around their mean. <br>
			Gen. is an abbreviation for the average. <br>
			The median is the middle value of all the values. <br>
			Var stands for the variance. It is a value that indicates the variability of all the values. ',
			'curveType' => 'Here you can choose whether you want a bar chart or a regular curve:',
			'normalCurve' => 'Normal function',
			'columCurve' => 'ColumnCurve',
			'note' => '(It does not work yet)',
			'userInput' => 'UserInput',
			'simpleCalc' => 'Simple Calculations',
			'advCalc' => 'Advanced Calculations',
			'enterValues' => 'Enter Values',
			'calcValues' => 'Calculated Values',
			'krl' => 'Kroner per liter',
			'kml' => 'Kilometers per liter',
			'kmkr' => 'Kilometer per kroner',
			'lkr' => 'Liter per kroner',
			'lkm' => 'Liter per kilometer',
			'krkm' => 'Kroner per kilometer',
			'km' => 'Kilometer',
			'median' => 'Median',
			'varians' => 'Variance',
			'stdev' => 'St. dev. ',
			'average' => 'Average',
		],
		'ownGraph' =>
		[
			'kmkrHeader' => 'Miles per kroner statistics:',
			'kmkrStdev' => 'Standard deviation for kilometers per kroner',
			'kmkrVar' => 'Variance for kilometers per kroner',
			'kmkrMedian' => 'Median for kilometers per kroner',
			'kmkrAverage' => 'Average for kilometers per kroner',
			'kmlHeader' => 'Miles per liter of statistics:',
			'kmlStdev' => 'Standard deviation for kilometers per liter',
			'kmlVar' => 'Variance for kilometers per liter',
			'kmlMedian' => 'Median for kilometers per liter',
			'kmlAverage '=>' Average per kilometer per liter ',
			'krHeader' => 'Crowns statistics:',
			'krStdev' => 'Standard deviation for kroner',
			'krVar' => 'Variance for kroner',
			'krMedian' => 'Median for kroner',
			'krAverage' => 'Average for kroner',
			'krkmHeader' => 'Kroner per kilometer statistics:',
			'krkmStdev' => 'Standard deviation for kroner per kilometer',
			'krkmVar' => 'Variance for kroner per kilometer',
			'krkmMedian' => 'Median for kroner per kilometer',
			'krkmAverage' => 'Average of kroner per kilometer',
			'krlHeader' => 'NOK per liter of statistics:',
			'krlStdev' => 'Standard deviation for kroner per liter',
			'krlVar' => 'Variance for kroner per liter',
			'krlMedian' => 'Median for kroner per liter',
			'krlAverage' => 'Average for kroner per liter',
			'lHeader' => 'Liter Statistics:',
			'lStdev' => 'Standard deviation liter',
			'lVar' => 'Variance for liters',
			'lMedian' => 'Median for liter',
			'lAverage' => 'Average per liter',
			'lkmHeader' => 'Liter per kilometer statistics:',
			'lkmStdev' => 'Standard deviation liters per kilometer',
			'lkmVar' => 'Variance for liters per kilometer',
			'lkmMedian' => 'Median per liter per kilometer',
			'lkmAverage' => 'Average per liter per kilometer',
			'lkrHeader' => 'Liter per kroner statistics:',
			'lkrStdev' => 'Standard deviation liters per kroner',
			'lkrVar' => 'Variance for liters per kilometer',
			'lkrMedian' => 'Median for liters per kroner',
			'lkrAverage' => 'Average for liters per kroner',
			'kmHeader' => 'Mileage statistics:',
			'kmStdev' => 'Standard deviation kilometers',
			'kmVar' => 'Variance for kilometers',
			'kmMedian' => 'Median for kroner',
			'kmAverage' => 'Average of kroner',
		],
	];
?>